apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: lbmv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lbmv
    app.kubernetes.io/part-of: byoc-app-dpeh
  name: lbmvvsdy
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: lbmv
    weight: null
status: {}
